CREATE ROLE readaccess;
GRANT CONNECT ON DATABASE "MyDatabase" TO readaccess;
GRANT USAGE ON SCHEMA public TO readaccess;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readaccess;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO readaccess;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT ON TABLES TO readaccess;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT ON SEQUENCES TO readaccess;

CREATE USER readonly WITH PASSWORD '<OBFUSCATED>';
GRANT readaccess TO readonly;
